name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - ROS_DISTRO: melodic
          - ROS_DISTRO: noetic
    env:
      CATKIN_LINT: pedantic 
      CLANG_FORMAT_CHECK: file
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
  arm_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: aarch64
          - arch: armv7
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu20.04
          run: |
            echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-latest.list
            apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
            apt update
            apt-get -y install ros-noetic-ros-base
            echo ::set-output name=uname::$(uname --m)
      - name: Get the output
        run: |
          echo "The uname output was ${{ steps.build.outputs.uname }}"
