name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - ROS_DISTRO: melodic
          - ROS_DISTRO: noetic
    env:
      CATKIN_LINT: pedantic 
      CLANG_FORMAT_CHECK: file
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
  arm_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: aarch64
          - arch: armv7
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu20.04
          run: |
            uname -a
            echo ::set-output name=uname::$(uname --m)
      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.build.outputs.uname }}"
